In [1]:
import os
import numpy as np
from PIL import Image
import cv2
import pickle


BASE_DIR = globals()['_dh'][0]
image_dir = os.path.join(BASE_DIR, "images")

face_cascade = cv2.CascadeClassifier('cascades/data/haarcascade_frontalface_alt2.xml')
recognizer = cv2.face.LBPHFaceRecognizer_create()

current_id = 0
label_ids = {}
y_labels = []
x_train = []


for root, dirs, files, in os.walk(image_dir):
	for file in files:
		if file.endswith("png") or file.endswith("jpg"):
			path = os.path.join(root, file)
			label = os.path.basename(os.path.dirname(path)).replace(" ","-").lower()
			#print(label,path)
			if not label in label_ids:

				label_ids[label] = current_id
				current_id += 1
			id_ = label_ids[label]
			print(label_ids)
			#y_labels.append(label)
			#x_train.append(path) # verify this image, turn into a NUMPY array, GRAY
			pil_image = Image.open(path).convert("L")
			image_array = np.array(pil_image, "uint8")
			print(image_array)


			faces = face_cascade.detectMultiScale(image_array, scaleFactor=1.5, minNeighbors=5)

			for(x,y,w,h) in faces:
				roi = image_array[y:y+h, x:x+w]
				x_train.append(roi)
				y_labels.append(id_)

with open("labels.pickle", 'wb') as f:
	pickle.dump(label_ids, f)

recognizer.train(x_train, np.array(y_labels))
recognizer.save("trained-model.yml")



{'kenneth': 0}
[[116 116 116 ... 152 153 153]
 [116 116 116 ... 151 152 152]
 [116 116 116 ... 149 150 151]
 ...
 [157 157 157 ... 226 229 232]
 [158 158 157 ... 221 224 226]
 [158 158 158 ... 219 221 223]]
{'kenneth': 0}
[[ 85  77  84 ... 191 195 197]
 [ 80  86  85 ... 189 191 192]
 [ 90  96  81 ... 190 190 189]
 ...
 [211 211 210 ... 100 103 101]
 [211 211 212 ... 106 104  98]
 [210 212 214 ... 105 106 103]]
{'kenneth': 0}
[[106 105 101 ... 109 108 123]
 [107 108 106 ... 105 106 123]
 [111 119 116 ... 100 108 124]
 ...
 [207 205 204 ... 200 201 200]
 [207 206 205 ... 199 199 198]
 [205 205 205 ... 200 200 199]]
{'kenneth': 0}
[[ 52  53  57 ... 254 254 254]
 [ 55  48  56 ... 254 254 254]
 [ 46  39  53 ... 254 254 254]
 ...
 [ 75  77  77 ... 144 115  82]
 [ 76  85  80 ... 192 147 120]
 [ 74  77  82 ... 195 195 161]]
{'kenneth': 0}
[[114 116 115 ... 115 112 107]
 [118 117 117 ... 116 113 110]
 [115 114 116 ... 117 107 106]
 ...
 [ 74  73  78 ... 100  82  78]
 [ 74  69  65 ...  86  82  7